name: Congrats on Push

on:
  push:
    branches:
      - main

jobs:
  send-congrats:
    runs-on: ubuntu-latest

    steps:
    - name: Send Congrats Comment
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const message = "Congratulations! Code has been pushed to the repository.";
          const octokit = context.octokit;
          await octokit.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.repository.id,
            body: message
          });

